# Docker Compose file for running Quepid in Production mode.
# Allows you to update your Quepid installation over time.

version: '3'
services:
  mysql:
    container_name: quepid_prod_db
    image: mysql:5.6.37
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  redis:
    container_name: quepid_prod_redis
    image: redis
    ports:
      - 6379:6379

  app:
    container_name: quepid_prod_app
    image: quepid/quepid_app
    environment:
      - PORT=80
      - RACK_ENV=production
      - RAILS_ENV=production
      - DB_ADAPTER=mysql2
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=quepid
      - REDIS_URL=redis://redis:6379/1
      - FORCE_SSL=false
      - MAX_THREADS=2
      - WEB_CONCURRENCY=2
      - SECRET_KEY_BASE=some_value_needed_here
    ports:
      - 3000:3000
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
